import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ids = ["SSG", "ISR", "SSR", "CSR"];

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex w-[1080px] h-[80px] justify-evenly items-center mx-auto my-10">
          {ids.map((id) => (
            <p key={id} className="text-[24px] font-bold">
              <Link href={`/${id.toLowerCase()}`}>{id}</Link>
            </p>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
